# Generated by Django 3.1.5 on 2026-04-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_moduleaccess_database'),
        ('scholarships', '0004_spacs_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_gold',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('Forwarded', 'FORWARDED')], default='INCOMPLETE', max_length=10),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('Forwarded', 'FORWARDED')], default='INCOMPLETE', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('Forwarded', 'FORWARDED')], default='INCOMPLETE', max_length=10),
        ),
        migrations.AlterField(
            model_name='previous_winner',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='status',
            field=models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('Forwarded', 'FORWARDED')], default='INCOMPLETE', max_length=10),
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(choices=[('mcm', 'MCM'), ('gold', 'Gold'), ('silver', 'Silver'), ('dm', 'DM')], max_length=10)),
                ('application_id', models.IntegerField()),
                ('note', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo')),
            ],
            options={
                'db_table': 'ApplicationNote',
            },
        ),
    ]
