# Generated by Django 3.1.5 on 2026-04-18 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260418_1243'),
        ('scholarships', '0005_auto_20260417_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforward',
            name='scholarship_type',
            field=models.CharField(choices=[('mcm', 'MCM'), ('gold', 'Gold'), ('silver', 'Silver'), ('dm', 'DM'), ('sp', 'Single Parent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='scholarship_type',
            field=models.CharField(choices=[('mcm', 'MCM'), ('gold', 'Gold'), ('silver', 'Silver'), ('dm', 'DM'), ('sp', 'Single Parent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='scholarship_type',
            field=models.CharField(choices=[('mcm', 'MCM Scholarship'), ('gold', "Director's Gold Medal"), ('silver', "Director's Silver Medal"), ('dm', 'D&M Proficiency Gold Medal'), ('sp', 'Single Parent Scholarship')], max_length=10),
        ),
        migrations.CreateModel(
            name='SingleParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('single_parent_name', models.CharField(max_length=50, null=True)),
                ('single_parent_occupation', models.CharField(max_length=100, null=True)),
                ('annual_income', models.IntegerField(default=0)),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('death_or_divorce_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('relevant_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('Complete', 'COMPLETE'), ('Incomplete', 'INCOMPLETE'), ('Reject', 'REJECT'), ('Accept', 'ACCEPT'), ('Forwarded', 'FORWARDED')], default='INCOMPLETE', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('award_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='scholarships.award_and_scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_parent_info', to='academic_information.student')),
            ],
            options={
                'db_table': 'SingleParent',
            },
        ),
    ]
