# Generated by Django 3.1.5 on 2026-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20260417_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_gold',
            name='status',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Incomplete', 'INCOMPLETE'), ('Forwarded', 'FORWARDED'), ('Accept', 'ACCEPT'), ('Reject', 'REJECT')], default='Incomplete', max_length=30),
        ),
        migrations.AlterField(
            model_name='director_silver',
            name='status',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Incomplete', 'INCOMPLETE'), ('Forwarded', 'FORWARDED'), ('Accept', 'ACCEPT'), ('Reject', 'REJECT')], default='Incomplete', max_length=30),
        ),
        migrations.AlterField(
            model_name='mcm',
            name='status',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Incomplete', 'INCOMPLETE'), ('Forwarded', 'FORWARDED'), ('Accept', 'ACCEPT'), ('Reject', 'REJECT')], default='Incomplete', max_length=30),
        ),
        migrations.AlterField(
            model_name='proficiency_dm',
            name='status',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Incomplete', 'INCOMPLETE'), ('Forwarded', 'FORWARDED'), ('Accept', 'ACCEPT'), ('Reject', 'REJECT')], default='Incomplete', max_length=30),
        ),
    ]
