# Generated by Django 3.1.5 on 2026-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_auto_20260418_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcm',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=10),
        ),
        migrations.AddField(
            model_name='mcm',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mcm',
            name='cpi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mcm',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mcm',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
